#! /bin/bash

config_dir=$(dirname $(realpath $0))
config=$config_dir/global_config.sh

echo "Appending repo config to .zshrc"
echo $config > ~/.machine_config_location
echo "source $config" >> ~/.zshrc

echo "Importing Config into current shell"
source $config
